In [1]:
import numpy 
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
arr=(3,4,5,6,7,8)
print(arr)

(3, 4, 5, 6, 7, 8)


In [7]:
import numpy as np
print(np.__version__)

1.26.4


In [9]:
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
import numpy as np
arr=np.array([1,23,4,556,6,5,35,44])
print(arr)
print(type(arr))


[  1  23   4 556   6   5  35  44]
<class 'numpy.ndarray'>


In [15]:
import numpy as np
arr=np.array((34,3,2,4,))
print(arr)
print(type(arr))

[34  3  2  4]
<class 'numpy.ndarray'>


In [24]:
import numpy as np                       //0-D array
numpy as np 
arr=np.array(43)
print(arr)

SyntaxError: invalid syntax (1628902993.py, line 1)

In [26]:
import numpy as np
arr=np.array(56)
print(arr)

56


In [28]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [30]:
import numpy as np 
arr=np.array([1,2,3],[4,5,6]])
print(arr)

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (2044622688.py, line 2)

In [32]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [36]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [38]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[4,5,6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [4 5 6]]]


In [46]:
import numpy as np
a=np.array(43)
b=np.array((1,2,3,4,5))
c=np.array(((1,2,3),(12,3,4)))
d=np.array((((2,3,4),(4,3,4),(4,54,4),(4,3,33))))
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
2


In [58]:
import numpy as np


arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions : ' , arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions :  5


In [56]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [1]:
import numpy as np
arr=np.array([4,5,43,34,])
print(arr[3])

34


In [7]:
import numpy as np 
arr = np.array([[1,2,3,4,5] ,[4,5,4,3,4]])
print('2nd element on 1st row :' , arr[1,4])

2nd element on 1st row : 4


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [15]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print([4:])

SyntaxError: invalid syntax (1664661606.py, line 5)

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [17]:
import numpy as np

arr = np.array([ 1, 2, 3, 4 , 5 , 6 ,7 ])

print(arr[:4])

[1 2 3 4]


In [19]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[1 : 5 : 2 ])



[2 4]


In [23]:
import numpy as np 
arr = np.array([1 , 23 , 4 , 5 ])

print(arr.dtype)
print(arr)

int32
[ 1 23  4  5]


In [25]:
import numpy as np

arr=np.array(['apple' , 'rida' , 'jahan'])

print(arr.dtype)
print(arr)

<U5
['apple' 'rida' 'jahan']
